### ISSUE TITLE
AVL Tree delete return wrong node

### ISSUE THREAD

**Issue by tckeong** [4ndrelim/data-structures-and-algorithms#83]
It seems like we need to make the return node become the node after rebalance in the delete function.
![image](https://github.com/4ndrelim/data-structures-and-algorithms/assets/86279038/f5f85ec2-b511-44a2-adf4-f8047e2479f2)

**Comment by 4ndrelim** [comment]
Ah, you're right. Will fix this shortly or feel free to raise a PR. It seems the suite of test cases aren't comprehensive enough, but then agn, testing this requires some set-up.

**Comment by 4ndrelim** [comment]
fixed. turns out the suite of test cases for avl tree wasn't uploaded.. so it missed it. Will look for the source test files and push soon! Thanks for the spot!
